#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!

# Update package lists
apt-get update

# Install nginx
apt-get install -y nginx

# Ensure nginx listens on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx to apply changes
service nginx restart

# Create a simple HTML file with "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

