#!/usr/bin/env bash
# Configure Nginx to have a custom 404 page

# Create a custom 404 page containing the string "Ceci n'est pas une page"
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Create a new Nginx configuration file for custom error handling
cat <<EOF | sudo tee /etc/nginx/sites-available/custom_404
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF

# Enable the custom 404 configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration for syntax errors
sudo nginx -t

# If the syntax is okay, reload Nginx to apply changes
if [ $? -eq 0 ]; then
    sudo systemctl reload nginx
fi

