#!/usr/bin/env bash
# Script that configures a brand new Ubuntu machine to the requirements asked

# Update package repositories
apt-get update

# Install Nginx
if ! apt-get -y install nginx; then
    echo "Failed to install Nginx. Exiting." >&2
    exit 1
fi

# Add custom HTTP header configuration to Nginx
if ! sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default; then
    echo "Failed to add custom header configuration to Nginx. Exiting." >&2
    exit 1
fi

# Restart Nginx
if ! service nginx restart; then
    echo "Failed to restart

