#!/usr/bin/env bash 

# Configure Nginx with custom HTTP response header
sudo apt update
sudo apt install nginx -y

# Add custom header configuration to Nginx
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    # Add custom header
    add_header X-Served-By $HOSTNAME;

}
EOF'

# Restart Nginx to apply changes
sudo systemctl restart nginx
