#!/usr/bin/env bash
# pings an IP address passed as an argument

if [ $# != 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Function to check if the IP address is valid
is_valid_ip() {
    local ip="$1"
    if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        return 0  # Valid IP address
    else
        return 1  # Invalid IP address
    fi
}

# Check if the provided argument is a valid IP address
if ! is_valid_ip "$1"; then
    echo "Invalid IP address: $1"
    exit 1
fi

# Ping the specified IP address
ping -c 5 "$1"

