#!/usr/bin/env bash
# Manages 'manage_my_process'

if [ "${1}" == "start" ]; then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]; then
    if [ -f /var/run/my_process.pid ]; then
        echo "manage_my_process stopped"
        pkill -F /var/run/my_process.pid
        rm /var/run/my_process.pid
    else
        echo "manage_my_process is not running"
    fi
elif [ "${1}" == "restart" ]; then
    if [ -f /var/run/my_process.pid ]; then
        echo "manage_my_process restarted"
        pkill -F /var/run/my_process.pid
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
    else
        echo "manage_my_process is not running. Starting a new instance."
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
