#!/usr/bin/env bash
# Bash script to display username, user id, and home directory path from /etc/passwd

# Use while loop to read each line of /etc/passwd
while IFS=: read -r username _ userid _ _ home_directory _
do
    # Display username, user id, and home directory path
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home_directory"
done < /etc/passwd

