#!/usr/bin/env bash
# displays Best School 10 times.

# Initialize counter
counter=0

# Until loop to display "Best School" until counter is greater than or equal to 10
until [ $counter -ge 10 ]
do
    # Display "Best School"
    echo "Best School"

    # Increment counter
    ((counter++))
done
