#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.

HOURS=0
while [ $HOURS -lt 12 ]
do
    echo "Hour: $HOURS"
    MINUTES=1
    while [ $MINUTES -lt 60 ]
    do
        echo "Minute: $MINUTES"
        ((MINUTES+=1))
    done
    ((HOURS+=1))
done

