#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.

HOURS=0
while [ $HOURS -lt 13 ]
do
    MINUTES=1
    while [ $MINUTES -lt 60 ]
    do
        printf "%02d:%02d\n" $HOURS $MINUTES
        ((MINUTES+=1))
    done
    ((HOURS+=1))
done

