#!/usr/bin/env bash
# Displays the content of the current working directory.

for file in *
do
    # Check if the file contains a dash
    if [[ $file == *-* ]]; then
        # Extract and display the part after the first dash
        echo "$file" | cut -d'-' -f2
    else
        # Display the entire filename for files without a dash
        echo "$file"
    fi
done

