#!/bin/bash

# Bash script to display all active IPv4 IPs

# Use the 'ip' command to get a list of all active interfaces and their IPs

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'
